export type Axis = 'x'|'y'|'z'|'w';
export interface Point4 { x:number; y:number; z:number; w:number }
export type MotionKind = 'rapid'|'cut'|'arc-cw'|'arc-ccw'|'cycle';
export interface Diagnostic { severity:'error'|'warning'|'info'; line:number; code:string; message:string }
export interface MotionSegment { id:string; line:number; raw:string; kind:MotionKind; plane:'G17'|'G18'|'G19'; start:Point4; end:Point4; machineStart:Point4; machineEnd:Point4; relativeStart:Point4; relativeEnd:Point4; workOffset:string; workOffsetValue:Point4; localOffset:Point4; toolLengthComp:number; center?:Point4; feed:number; spindle:number; tool:number; estimatedSeconds:number; rotaryCode:31|32|33|34; rotaryAngle:number }
export interface ParsedBlock { line:number; raw:string; normalized:string; words:Record<string,number>; motion?:MotionSegment; motions?:MotionSegment[]; diagnostics:Diagnostic[] }
export interface ProgramSource { name:string; text:string; lineMap?:number[] }
export interface VariableWrite { line:number; variable:number; value:number; kind:'local'|'common'|'permanent'|'tool-offset'|'work-offset' }
export interface MacroCallTrace { line:number; program:string; repeat:number; arguments:Record<string,{variable:number;value:number}> }
export interface ParseResult { source:ProgramSource; blocks:ParsedBlock[]; segments:MotionSegment[]; diagnostics:Diagnostic[]; complete:boolean; variableWrites:VariableWrite[]; macroCalls:MacroCallTrace[]; finalVariables:Record<string,number>; finalToolGeometry:Record<string,number>; finalToolWear:Record<string,number>; finalWorkOffsets:Record<WorkOffsetCode,Point4>; finalSpindleTool:number; finalPendingTool:number; bounds:{min:Point4;max:Point4}; totals:{rapidDistance:number;cutDistance:number;estimatedSeconds:number;tools:number[]} }
export interface ToolAssembly { number:number; diameter:number; fluteLength:number; shaftDiameter:number; holderDiameter:number; holderLength:number }
export type WorkOffsetCode='G54'|'G55'|'G56'|'G57'|'G58'|'G59';
export interface MachineConfig { units:'mm'; limits:{x:[number,number];y:[number,number];z:[number,number];w:[number,number]}; initialMachinePosition:Point4; initialMachinePositionConfigured:boolean; rapidRate:number; optionalBlockSkip:boolean; g83Clearance:number; g83ClearanceConfigured:boolean; toolMagazineCapacity:number; toolMagazine:Record<string,number>; table:{x:number;y:number;z:number}; rotary:{enabled:boolean;centerX:number;centerY:number;centerZW:number;length:number;stockWidth:number;stockHeight:number;zeroCode:31|32|33|34;direction:1|-1}; stock:{shape:'box'|'cylinder';x:number;y:number;z:number;diameter:number;origin:Point4}; fixtures:Array<{id:string;shape:'box'|'cylinder';x:number;y:number;z:number;diameter:number;origin:Point4}>; tools:ToolAssembly[]; toolOffsetMemory:'A'|'B'; toolOffsetCount:32|64|99|200|400; additionalCommonVariables:boolean; toolLengthOffsets:Record<string,number>; toolWearOffsets:Record<string,number>; customVariables:Record<string,number>; workOffsets:Record<WorkOffsetCode,Point4> }
export interface CollisionEvent { line:number; type:'overtravel'|'rapid-stock'|'tool-fixture'|'holder-stock'|'undefined-tool'; message:string; severity:'error'|'warning' }
export interface ComparisonReport { lineChanges:number; maxDeviation:number; meanDeviation:number; timeDelta:number }
